color: teal
fieldLayouts:
  5729310c-3ea6-42f8-8947-2566188bb614:
    cardView:
      - 'layoutElement:c4f16b55-1f41-401a-b093-f360e013fbe0'
      - 'layoutElement:17c79c1b-dba6-4c1e-8db3-6d3aaabfaa91'
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-12-20T15:38:33+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: a3045613-418c-483e-a666-fb4269b18c80 # URL
            handle: null
            includeInCards: true
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 17c79c1b-dba6-4c1e-8db3-6d3aaabfaa91
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-12-20T15:38:33+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 4381ddb2-8940-4d25-8e42-5a770b533b71 # Tekst
            handle: labelField
            includeInCards: true
            instructions: null
            label: Label
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c4f16b55-1f41-401a-b093-f360e013fbe0
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-12-20T15:38:33+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 9711e272-d70a-4399-adde-7368c097f72c # Doel
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5282cba7-8acf-46e1-b231-89a9ec58e01b
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-22T21:49:51+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 7947a42a-167a-4d11-a4c2-dcf9fa46eb65 # Knop variant
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 084fd2e5-6bb1-4d5f-92a6-c10e55c57308
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: f9e1cc15-c079-4dcd-95e2-2d2d9a1aa357
        userCondition: null
handle: button
hasTitleField: false
icon: square
name: Knop
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
