color: orange
fieldLayouts:
  4fba09ff-b778-4c15-91c3-133dcc92e18c:
    cardView:
      - 'layoutElement:2e2ecf6c-b17d-43b3-9276-f44ee05fc30d'
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-06-19T21:49:44+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 9a80c602-8f9a-47fa-9f77-bec83a7c2418 # Foto
            handle: thumbnailField
            includeInCards: false
            instructions: null
            label: Thumbnail
            providesThumbs: true
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7000e2f0-5789-41da-b362-be13f3b97a02
            userCondition: null
            warning: null
            width: 100
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-06-19T21:47:46+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: f081d7c1-6f43-47d9-b1b7-3bd58671cb8c
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2025-06-19T22:23:51+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 96e0badb-3ddd-4fab-8fdf-99eb1091225b # Price
            handle: priceField2
            includeInCards: true
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2e2ecf6c-b17d-43b3-9276-f44ee05fc30d
            userCondition: null
            warning: null
            width: 50
        name: Content
        uid: 16b0c639-6be8-4316-b77d-9006bfd5c770
        userCondition: null
handle: drink
hasTitleField: true
icon: beer-mug
name: Drankje
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
