allowPublicRegistration: false
deactivateByDefault: false
defaultGroup: ''
photoSubpath: '{username}'
photoVolumeUid: a0e451ef-63a0-4743-b8ed-d7b329262efe # User profile images
require2fa: false
requireEmailVerification: true
validateOnPublicRegistration: false
