cardView:
  - lastName
  - firstName
tabs:
  -
    elementCondition: null
    elements:
      -
        dateAdded: '2025-06-24T21:04:28+00:00'
        elementCondition: null
        id: null
        includeInCards: false
        instructions: null
        label: null
        orientation: null
        providesThumbs: false
        requirable: false
        tip: null
        type: craft\fieldlayoutelements\users\PhotoField
        uid: cba8f52f-0d4a-458f-9990-fde793dcd56a
        userCondition: null
        warning: null
        width: 100
      -
        autocapitalize: true
        autocomplete: false
        autocorrect: true
        class: null
        dateAdded: '2025-06-24T21:04:28+00:00'
        disabled: false
        elementCondition: null
        id: null
        includeInCards: false
        inputType: null
        instructions: null
        label: null
        max: null
        min: null
        name: null
        orientation: null
        placeholder: null
        providesThumbs: false
        readonly: false
        requirable: false
        size: null
        step: null
        tip: null
        title: null
        type: craft\fieldlayoutelements\users\EmailField
        uid: 38afdbc3-e4c9-4f3c-8edf-73f736fabfea
        userCondition: null
        width: 50
      -
        dateAdded: '2025-06-24T21:14:51+00:00'
        editCondition: null
        elementCondition: null
        fieldUid: 4381ddb2-8940-4d25-8e42-5a770b533b71 # Tekst
        handle: memberId
        includeInCards: false
        instructions: null
        label: Lidnummer
        providesThumbs: false
        required: false
        tip: null
        type: craft\fieldlayoutelements\CustomField
        uid: 904dedd9-5661-4c7d-8a38-575ebab0e251
        userCondition: null
        warning: null
        width: 50
      -
        dateAdded: '2025-06-24T21:18:22+00:00'
        editCondition: null
        elementCondition: null
        fieldUid: 6472ea84-e89e-4546-89fb-15865f4a2f73 # Ploegen
        handle: null
        includeInCards: false
        instructions: null
        label: null
        providesThumbs: false
        required: false
        tip: null
        type: craft\fieldlayoutelements\CustomField
        uid: fa382ed4-a119-4069-8247-0d452fa8ac35
        userCondition: null
        warning: null
        width: 100
      -
        autocapitalize: true
        autocomplete: false
        autocorrect: true
        class: null
        dateAdded: '2025-06-24T21:04:28+00:00'
        disabled: false
        elementCondition: null
        id: null
        includeInCards: false
        inputType: null
        instructions: null
        label: null
        max: null
        min: null
        name: null
        orientation: null
        placeholder: null
        providesThumbs: false
        readonly: false
        requirable: false
        size: null
        step: null
        tip: null
        title: null
        type: craft\fieldlayoutelements\users\UsernameField
        uid: ba968dd1-920f-4af3-ba6d-c55ff78d6f35
        userCondition: null
        warning: null
        width: 100
      -
        attribute: fullName
        autocapitalize: true
        autocomplete: false
        autocorrect: true
        class: null
        dateAdded: '2025-06-24T21:04:28+00:00'
        disabled: false
        elementCondition: null
        id: null
        includeInCards: false
        inputType: null
        instructions: null
        label: null
        max: null
        min: null
        name: null
        orientation: null
        placeholder: null
        providesThumbs: false
        readonly: false
        requirable: true
        required: false
        size: null
        step: null
        tip: null
        title: null
        type: craft\fieldlayoutelements\users\FullNameField
        uid: ba286347-ec6c-48e6-aaa3-5a60cc5f1ebf
        userCondition: null
        warning: null
        width: 100
    name: Inhoud
    uid: ed765836-70ea-4a78-b693-cf76b46f3fcc
    userCondition: null
