altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  29a7767d-5db0-4351-90ba-59f82d85c064:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-06-19T21:24:33+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 36127f23-fd26-4db5-95a4-e08d75e14af8
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 17483b69-789f-4c86-8c2f-17250a50b7f9
        userCondition: null
fs: usersFileSystem
handle: userProfileImagesVolume
name: 'User profile images'
sortOrder: 2
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
