columnSuffix: null
handle: buttonsField
instructions: null
name: Buttons
searchable: true
settings:
  createButtonLabel: 'New button'
  defaultIndexViewMode: cards
  entryTypes:
    - aa95f819-8179-4afd-8972-f3d4b77f3056 # Knop
  includeTableView: false
  maxEntries: null
  minEntries: null
  pageSize: 50
  propagationKeyFormat: null
  propagationMethod: all
  showCardsInGrid: true
  viewMode: cards
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
