columnSuffix: null
handle: priceField
instructions: null
name: Price
searchable: true
settings:
  currency: EUR
  defaultValue: 0
  max: null
  min: 0
  showCurrency: true
  size: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Money
