dateModified: 1750619525
elementSources:
  craft\elements\Asset:
    -
      defaultSort:
        - dateCreated
        - desc
      defaultViewMode: ''
      disabled: false
      key: 'volume:78f386d8-ccbe-4fa9-b24b-f527005175e6' # Uploads
      tableAttributes:
        - filename
        - size
        - imageSize
        - kind
        - link
      type: native
    -
      key: 'volume:a0e451ef-63a0-4743-b8ed-d7b329262efe' # User profile images
      type: native
    -
      key: temp
      type: native
  craft\elements\Entry:
    -
      defaultSort:
        - postDate
        - desc
      defaultViewMode: ''
      disabled: true
      key: '*'
      tableAttributes:
        - status
        - section
        - postDate
        - expiryDate
        - link
      type: native
    -
      defaultSort:
        - title
        - asc
      defaultViewMode: ''
      disabled: true
      key: singles
      tableAttributes:
        - status
        - link
      type: native
    -
      heading: Pages
      type: heading
    -
      condition:
        class: craft\elements\conditions\entries\EntryCondition
        conditionRules:
          -
            class: craft\elements\conditions\entries\SectionConditionRule
            operator: in
            uid: 2d9c68f9-41eb-4405-b070-1542e1b3bfd5
            values:
              - 5b185af0-6204-4ae7-8d25-bf9ef8208ad0
        elementType: craft\elements\Entry
        fieldContext: global
      defaultSort:
        - title
        - asc
      defaultViewMode: table
      key: 'custom:04fa9561-5f43-4a9c-bc6e-68cce3b05fd2'
      label: 'Default pages'
      tableAttributes:
        - uri
        - dateUpdated
        - status
      type: custom
    -
      defaultSort:
        - structure
        - asc
      defaultViewMode: ''
      disabled: false
      key: 'section:eb0d0935-3bc1-4cf1-86d9-275a753716de' # Extra Pagina's
      tableAttributes:
        - uri
        - dateUpdated
        - status
      type: native
    -
      heading: General
      type: heading
    -
      defaultSort:
        - structure
        - asc
      defaultViewMode: ''
      disabled: false
      key: 'section:24822cfe-6970-4a10-a176-a5078e260577' # Drankjes
      tableAttributes:
        - 'fieldInstance:2e2ecf6c-b17d-43b3-9276-f44ee05fc30d'
        - revisionCreator
        - postDate
        - status
      type: native
email:
  fromEmail: dev@manu.be
  fromName: 'HNO Assenede'
  replyToEmail: null
  template: null
  transportSettings:
    command: '/usr/local/bin/mailpit sendmail -t --smtp-addr 127.0.0.1:1025'
  transportType: craft\mail\transportadapters\Sendmail
fs:
  publicFilesystem:
    hasUrls: true
    name: Public
    settings:
      path: '@webroot/uploads'
    type: craft\fs\Local
    url: $PRIMARY_SITE_URL/uploads
  usersFileSystem:
    hasUrls: true
    name: Users
    settings:
      path: '@webroot/users'
    type: craft\fs\Local
    url: $PRIMARY_SITE_URL/users
meta:
  __names__:
    00e1d9bb-51b9-4ebf-847e-a089feaef726: 'Public Schema' # Public Schema
    2ab57b6f-1852-449c-9afa-30c833317b58: Linken # Linken
    2b9c20b9-9252-416a-b5a0-041473c84c8a: Icoon # Icoon
    4b9c49b3-1c60-4cf8-90ea-24baf113c4ee: SEO # SEO
    6a670d1f-08c6-4670-a8d8-30615c588e2f: Knop # Knop
    8ec97a19-2e28-4350-b8a9-78fc2b8a06e2: 'HNO Assenede' # HNO Assenede
    8eceae5c-bf72-475b-a84f-33735f3d3f1d: Title # Title
    9a80c602-8f9a-47fa-9f77-bec83a7c2418: Foto # Foto
    28efc0ec-8432-4ee6-b8ad-5b109779166c: Link # Link
    39dae8e0-9ae7-4d95-9088-aa5a0af11cbe: Images # Images
    78f386d8-ccbe-4fa9-b24b-f527005175e6: Uploads # Uploads
    96e0badb-3ddd-4fab-8fdf-99eb1091225b: Price # Price
    841b576a-8964-4701-ac7a-8789c2ee20d1: 'Primaire navigatie' # Primaire navigatie
    857c718e-b5a7-402c-8bcd-e92b86306176: 'Rich text' # Rich text
    883ee07a-821a-4772-acaf-e9a78ff34015: 'Footer navigatie' # Footer navigatie
    4381ddb2-8940-4d25-8e42-5a770b533b71: Tekst # Tekst
    4873bc46-6c2c-4e5a-8e84-cb8e312f20ad: Buttons # Buttons
    05248eae-0d0d-4c9b-9c0f-da2e1ec1213a: Link # Link
    7947a42a-167a-4d11-a4c2-dcf9fa46eb65: 'Knop variant' # Knop variant
    9711e272-d70a-4399-adde-7368c097f72c: Doel # Doel
    24822cfe-6970-4a10-a176-a5078e260577: Drankjes # Drankjes
    61469d6d-683d-43fa-a8e6-3c2cb67cab85: Drankje # Drankje
    a0e451ef-63a0-4743-b8ed-d7b329262efe: 'User profile images' # User profile images
    a3045613-418c-483e-a666-fb4269b18c80: URL # URL
    aa95f819-8179-4afd-8972-f3d4b77f3056: Knop # Knop
    d0499f4d-e39e-4fab-80c5-595fadbfcf91: 'Meerdere lijnen tekst' # Meerdere lijnen tekst
    d1ab0c28-7124-4171-99dd-27b8f9805017: 'Opgemaakte Tekst' # Opgemaakte Tekst
    d7e8d0bc-8052-499d-99b8-d622687dfee7: Page # Page
    e1acd264-0533-4dd7-8cfa-183423e1c25e: nl # nl
    e7f650f0-adf2-4ec9-95af-8db8542b1931: Titel # Titel
    eb0d0935-3bc1-4cf1-86d9-275a753716de: "Extra Pagina's" # Extra Pagina's
plugins:
  ckeditor:
    edition: standard
    enabled: true
    schemaVersion: 3.0.0.0
  cp-field-inspect:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  seo:
    edition: standard
    enabled: true
    schemaVersion: 3.2.0
    settings:
      description: ''
      facebookAppId: ''
      metaTemplate: ''
      removeAlternateUrls: ''
      robots:
        - ''
        - ''
        - ''
        - ''
        - ''
        - ''
      robotsTxt: "{# Sitemap URL #}\r\nSitemap: {{ url(seo.sitemapName ~ '.xml') }}\r\n\r\n{# Disallows #}\r\n{% if craft.app.config.env != 'production' %}\r\n\r\n{# Disallow access to everything when NOT in production #}\r\nUser-agent: *\r\nDisallow: /\r\n\r\n{% else %}\r\n\r\n{# Disallow access to cpresources/ when live #}\r\nUser-agent: *\r\nDisallow: /cpresources/\r\n\r\n{% endif %}"
      sitemapLimit: '1000'
      sitemapName: sitemap
      socialImage: ''
      title:
        -
          __assoc__:
            -
              - key
              - '1'
            -
              - locked
              - '0'
            -
              - template
              - '{title}'
        -
          __assoc__:
            -
              - key
              - '2'
            -
              - locked
              - '1'
            -
              - template
              - ' - {{ systemName }}'
      titleSuffix: null
      twitterHandle: ''
  vite:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
system:
  edition: pro
  live: true
  name: 'HNO Assenede'
  retryDuration: null
  schemaVersion: 5.7.0.3
  timeZone: Europe/Brussels
