defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 82998132-6d0e-46f2-b2c5-44d619da765c # Wedstrijd
handle: competitions
maxAuthors: 1
name: Wedstrijden
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primaire invoer-pagina'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  e1acd264-0533-4dd7-8cfa-183423e1c25e: # nl
    enabledByDefault: true
    hasUrls: true
    template: _app/pages/competitions/entry.twig
    uriFormat: 'wedstrijden/{slug}'
structure:
  maxLevels: 1
  uid: 972f4a1c-8b08-4df6-a9a7-35608e924832
type: structure
